---
title: Kai Gradert - New
timezone: America/Los_Angeles
collections:
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: '/blog/:title/'
    layout: page
description: I am a designer at AngelList. Currently living in California. My interests
  range from photography to technology.
author: Kai Gradert
bio: Designer, Photographer, Father
keywords: User Experience, Visual Design, UX, Design, Google, Apple, Consulting
email: kai.gradert@gmail.com
gravatar: 11e4ed5d85b6bccce20f8f86476785d6
url: http://kaigradert.com
contact:
  AngelList: https://angel.co/kai
  Flickr: http://www.flickr.com/photos/kaigradert/sets/
  Google: https://plus.google.com/+KaiGradert/
  Instagram: http://instagram.com/kaikemono
  LinkedIn: http://www.linkedin.com/in/kaigradert
  SmugMug: https://kaigradert.smugmug.com/
  Twitter: https://twitter.com/kaigradert
# Feed: "/feed.xml"
baseurl:
permalink: pretty
markdown: kramdown
gems:
- jekyll-feed
# - jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- config.codekit3
- styles/global.sass
