# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:            Kai Gradert
url:              http://kaigradert.com # the base hostname & protocol for your site, e.g. http://example.com
timezone:         UTC
permalink:        pretty
email:            kai.gradert@gmail.com
description:      Write an awesome description for your new site here.
baseurl:          "" # the subpath of your site, e.g. /blog

collections:
  uploads:
    title: Uploads
    output: true
  blog:
    output: true
  work:
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "//Users/kai/Dropbox/Projects/Siteleaf/siteleaf_kaigradert_export /:title/"

markdown:         kramdown
theme:            minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock