---
title: Kai Gradert New
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: kai.gradert@gmail.com
description: New site using Siteleaf v2.
baseurl: 
url: 
twitter_username: kaigradert
github_username: kaigradert
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
