---
title: Kai Gradert v2
timezone: America/Los_Angeles
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: ''
    layout: ''
- scope:
    path: projects
    type: posts
  values:
    layout: ''
    author: ''
description: Write an awesome description for your new site here.
url: http://kaigradert.com
baseurl: 
permalink: pretty
email: kai.gradert@gmail.com
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- config.codekit3
- styles/global.sass
